# apobec_de.R

# Differential expression from stats files generated by GDAC_preprocess.R

library(gplots)

root <- '/Users/jiachen/OneDrive - OnTheHub - The University of Oxford/Buffa Lab/apobec/data/stats/'
setwd(root)

# Cancer list
cancers <- as.character(read.table('/Users/jiachen/OneDrive - OnTheHub - The University of Oxford/Buffa Lab/apobec/data/cancer_list.txt', header=T, sep='\t')[,1])

# APOBEC
de_apo <- matrix(nrow=12, ncol=0)
for(c in cancers){
  input <- read.table(paste(c, '_de_a.txt', sep=''), sep='\t', header=T, row.names=1)
  cur <- input$DE.using.Mean
  de_apo <- cbind(de_apo, cur)
  rownames(de_apo) <- rownames(input)
}
de_apo <- de_apo[order(rownames(de_apo)),]
colnames(de_apo) <- cancers

# Hypoxia
de_hyp <- matrix(nrow=52, ncol=0)
for(c in cancers){
  input <- read.table(paste(c, '_de_h.txt', sep=''), sep='\t', header=T, row.names=1)
  cur <- input$DE.using.Mean
  de_hyp <- cbind(de_hyp, cur)
  rownames(de_hyp) <- rownames(input)
}
de_hyp <- de_hyp[order(rownames(de_hyp)),]
colnames(de_hyp) <- cancers

# Heatmap
dir_o <- '/Users/jiachen/OneDrive - OnTheHub - The University of Oxford/Buffa Lab/apobec/output/'
pdf(file=paste(dir_o, 'APOBEC_DE.pdf', sep=''), width=8, height=8)
hm <- heatmap.2(
  de_apo,
  Rowv=NA, Colv=NA,
  xlab = 'Cancers',
  main = 'Log fold change',
  dendrogram="none", density.info="none", trace="none",
  col=bluered,
  breaks=seq(-4, 4, length.out=101),
  margins=c(7,7)
)
dev.off()
pdf(file=paste(dir_o, 'APOBEC_DE_clustered.pdf', sep=''), width=8, height=8)
hm <- heatmap.2(
  de_apo,
  xlab = 'Cancers',
  main = 'Log fold change',
  density.info="none", trace="none",
  col=bluered,
  breaks=seq(-4, 4, length.out=101),
  margins=c(7,7)
)
dev.off()